name: Deploy Application
on:
  push:
    branches:
      - master
      - github-ci

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build image
        run: docker build -t go-lunch -f Dockerfile .

      - name: Prepare SSH key
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PKEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: Build APP
        run: docker run -t --volume $(pwd)/bin:/app/bin go-lunch

      - name: Stop project
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.PROD_SSH_HOST }} 'supervisorctl stop go-lunch'

      - name: Copy built file
        run: |
          scp -o StrictHostKeyChecking=no $(pwd)/bin/go-lunch ${{ secrets.SSH_USER }}@${{ secrets.PROD_SSH_HOST }}:${{ secrets.PROD_PROJECT_ROOT }}/go-lunch

      - name: Start project
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.PROD_SSH_HOST }} 'supervisorctl start go-lunch'
